#!/usr/bin/env python3
"""Emit a supabase-js compatible `Database` type from a migrated database.
Usage: python3 scripts/gen-types.py [dbname] > src/lib/supabase/database.types.ts
(`supabase gen types typescript --local` produces an equivalent file once the
Supabase CLI stack is running; this script only needs psql.)"""
import json, os, shlex, subprocess, sys

db = sys.argv[1] if len(sys.argv) > 1 else "growth_os_test"
psql = shlex.split(os.environ.get("PSQL", "psql"))

def q(sql):
    return json.loads(subprocess.check_output(psql + ["-X", "-At", "-d", db, "-c", sql], text=True) or "null") or []

SCALAR = {
    "uuid": "string", "text": "string", "citext": "string", "character": "string", "bpchar": "string",
    "character varying": "string", "inet": "string", "date": "string", "time without time zone": "string",
    "timestamp with time zone": "string", "timestamp without time zone": "string", "interval": "string",
    "integer": "number", "bigint": "number", "smallint": "number", "numeric": "number", "double precision": "number",
    "real": "number", "boolean": "boolean", "jsonb": "Json", "json": "Json", "void": "undefined",
}
def ts(t):
    t = t.split("(")[0].strip()
    if t.endswith("[]"): return f"{ts(t[:-2])}[]"
    t = t.replace("extensions.", "")
    return SCALAR.get(t, "unknown")

rels = q("""
select json_agg(json_build_object('name', c.relname, 'kind', c.relkind, 'cols',
  (select json_agg(json_build_object('n', a.attname, 't', format_type(a.atttypid, a.atttypmod),
      'nn', a.attnotnull, 'def', a.atthasdef or a.attidentity <> '') order by a.attnum)
   from pg_attribute a where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)) order by c.relname)
from pg_class c join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relkind in ('r', 'v')""")

fns = q("""
select json_agg(json_build_object('name', p.proname, 'args', coalesce(p.proargnames, '{}'),
  'modes', coalesce(p.proargmodes::text[], '{}'), 'alltypes',
  (select coalesce(json_agg(format_type(t, null) order by o), '[]') from unnest(coalesce(p.proallargtypes, p.proargtypes::oid[])) with ordinality u(t, o)),
  'ndef', p.pronargdefaults, 'nin', p.pronargs, 'ret', format_type(p.prorettype, null), 'set', p.proretset) order by p.proname)
from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'app'""")

out = ["// Generated by scripts/gen-types.py. Do not edit by hand.",
       "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];", "",
       "export type Database = {", "  public: {", "    Tables: {"]
for r in [r for r in rels if r["kind"] == "r"]:
    cols = r["cols"]
    out.append(f"      {r['name']}: {{")
    out.append("        Row: { " + "; ".join(f"{c['n']}: {ts(c['t'])}{'' if c['nn'] else ' | null'}" for c in cols) + " };")
    out.append("        Insert: { " + "; ".join(f"{c['n']}{'?' if (c['def'] or not c['nn']) else ''}: {ts(c['t'])}{'' if c['nn'] else ' | null'}" for c in cols) + " };")
    out.append("        Update: { " + "; ".join(f"{c['n']}?: {ts(c['t'])}{'' if c['nn'] else ' | null'}" for c in cols) + " };")
    out.append("        Relationships: [];")
    out.append("      };")
out += ["    };", "    Views: {"]
for r in [r for r in rels if r["kind"] == "v"]:
    out.append(f"      {r['name']}: {{")
    out.append("        Row: { " + "; ".join(f"{c['n']}: {ts(c['t'])} | null" for c in r["cols"]) + " };")
    out.append("        Relationships: [];")
    out.append("      };")
out += ["    };", "    Functions: { [_ in never]: never };", "    Enums: { [_ in never]: never };",
        "    CompositeTypes: { [_ in never]: never };", "  };", "  app: {",
        "    Tables: { [_ in never]: never };", "    Views: { [_ in never]: never };", "    Functions: {"]
for f in fns:
    names, modes, types = f["args"], f["modes"], f["alltypes"]
    if not modes: modes = ["i"] * len(types)
    ins = [(n, t) for n, m, t in zip(names, modes, types) if m in ("i", "b")]
    outs = [(n, t) for n, m, t in zip(names, modes, types) if m in ("o", "t")]
    first_default = len(ins) - f["ndef"]
    args = "; ".join(f"{n}{'?' if i >= first_default else ''}: {ts(t)}" for i, (n, t) in enumerate(ins))
    if outs:
        ret = "{ " + "; ".join(f"{n}: {ts(t)} | null" for n, t in outs) + " }[]"
    else:
        ret = ts(f["ret"]) + ("[]" if f["set"] else "")
    out.append(f"      {f['name']}: {{ Args: {{ {args} }}; Returns: {ret} }};" if args else
               f"      {f['name']}: {{ Args: Record<PropertyKey, never>; Returns: {ret} }};")
out += ["    };", "    Enums: { [_ in never]: never };", "    CompositeTypes: { [_ in never]: never };", "  };", "};", "",
        "type PublicSchema = Database['public'];",
        "export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row'];",
        "export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert'];",
        "export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update'];",
        "export type Views<T extends keyof PublicSchema['Views']> = PublicSchema['Views'][T]['Row'];",
        "export type AppFunctions = Database['app']['Functions'];", ""]
print("\n".join(out))
